In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm
import os
import pprint

In [2]:
print("a;sdmas")

a;sdmas


In [3]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr2.dtype

dtype('int32')

In [6]:
arr = np.array([1, 2, 4, 5, 6], dtype=np.int32)
float_arr = arr.astype(np.float64)

In [7]:
float_arr.dtype

dtype('float64')

In [8]:
arr.dtype

dtype('int32')

In [9]:
data = np.random.randn(2, 5)

In [10]:
data

array([[-0.64584069,  0.18863952, -0.51181037, -0.34328715, -1.11043332],
       [-0.73212978, -1.10438776, -0.01107123,  0.21168687, -1.15850378]])

In [11]:
data + data

array([[-1.29168137,  0.37727904, -1.02362075, -0.68657431, -2.22086664],
       [-1.46425956, -2.20877552, -0.02214246,  0.42337373, -2.31700755]])

In [12]:
data ^ 2

TypeError: ufunc 'bitwise_xor' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [14]:
data ** 2

array([[4.17110192e-01, 3.55848687e-02, 2.61949859e-01, 1.17846071e-01,
        1.23306216e+00],
       [5.36014015e-01, 1.21967232e+00, 1.22572181e-04, 4.48113293e-02,
        1.34213100e+00]])

In [17]:
data

array([[-0.64584069,  0.18863952, -0.51181037, -0.34328715, -1.11043332],
       [-0.73212978, -1.10438776, -0.01107123,  0.21168687, -1.15850378]])

In [18]:
( data * 3 ) ** 3

array([[-7.27344179e+00,  1.81243239e-01, -3.61985370e+00,
        -1.09228614e+00, -3.69692994e+01],
       [-1.05956592e+01, -3.63687619e+01, -3.66396768e-05,
         2.56121186e-01, -4.19813235e+01]])

In [19]:
data[0][1]

0.18863952043167065

In [20]:
data[0][1] * 3

0.565918561295012

In [21]:
x = data[0][1] * 3
x ** 3

0.18124323912771642

In [2]:
i = np.array(range(10), dtype=np.int32)

NameError: name 'np' is not defined

In [3]:
i

NameError: name 'i' is not defined

In [4]:
i = np

NameError: name 'np' is not defined

In [5]:
import numpy as np
i = np.array(range(10))
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
list(i)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]